/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hashcodes;

//import static com.mycompany.hashcodes.principal.selecPersona;
//import static com.mycompany.hashcodes.principal.vacunados;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC1
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        txtCUI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMostrar = new javax.swing.JLabel();
        txtMostrarV2 = new javax.swing.JLabel();
        txtMostrarV1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Vacunacion");

        txtMostrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMostrar.setText("CUI");
        txtMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtMostrarV2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMostrarV2.setText("Vacunacion 2");
        txtMostrarV2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMostrarV2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtMostrarV1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMostrarV1.setText("Vacunacion 1");
        txtMostrarV1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMostrarV1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCUI)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMostrarV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMostrarV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(txtCUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnImprimir))
                .addGap(23, 23, 23)
                .addComponent(txtMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtMostrarV1)
                .addGap(23, 23, 23)
                .addComponent(txtMostrarV2)
                .addGap(24, 24, 24))
        );

        txtMostrarV1.getAccessibleContext().setAccessibleName("Vacunacion 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            imprimir();
        } catch (IOException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    static Map<String, Personas> vacunados = new HashMap<>();
    static Personas selecPersona;
    
    public void buscar(){
        
        
        Personas persona1 = new Personas("2453285791901",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"19/01/2022\"}]"
                ,"[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"19/02/2022\"}]");
       
        vacunados.put(persona1.getCui(), persona1);
        
        Personas persona2 = new Personas("2453285791902",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"19/01/2022\"}]", null);
        
        vacunados.put(persona2.getCui(), persona2);
        
        Personas persona3 = new Personas("2453285791903",
                "[[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"01/01/2022\"}]",
                "[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"01/02/2022\"}]");
        
        
        vacunados.put(persona3.getCui(), persona3);
        
        Personas persona4 = new Personas("2453285791904",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"01/01/2022\"}]",
                "[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"01/02/2022\"}]");
        
        vacunados.put(persona4.getCui(), persona4);
        
        Personas persona5 = new Personas("2453285791905",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"19/01/2022\"}]"
                ,"[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"19/02/2022\"}]");
        
        vacunados.put(persona5.getCui(), persona5);
        
        Personas persona6 = new Personas("2453285791906",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"19/01/2022\"}]", null);
        
        vacunados.put(persona6.getCui(), persona6);
        
        Personas persona7 = new Personas("2453285791907",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"01/01/2022\"}],",
                "[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"01/02/2022\"}]");
        
        vacunados.put(persona7.getCui(), persona7);
        
        Personas persona8 = new Personas("2453285791908",
                "[{\"vacuna\":\"covid dosis 1\",\"fecha\":\"01/01/2022\"}],",
                "[{\"vacuna\":\"covid dosis 2\",\"fecha\":\"01/02/2022\"}]");
        
        vacunados.put(persona8.getCui(), persona8);
        
        
        selecPersona = new Personas(null, null, null);
        
        selecPersona.setCui(txtCUI.getText());
        
        if(!vacunados.containsKey(selecPersona.getCui())){
            
            txtMostrar.setText("Persona no registrada");  
            txtMostrarV1.setText("");
            txtMostrarV2.setText("");
            
        }else{
            
            for (var entry : vacunados.entrySet()) {
            Personas persona = entry.getValue();
            
            
            if (selecPersona.equals(persona)){
                //System.out.println(persona.getCui() + ":" + persona.getInfo());  
                txtMostrar.setText(persona.getCui());
                if(persona.getInfo() == null){
                    txtMostrarV1.setText("No ha vacunado");
                    txtMostrarV2.setText("Necesita primera dosis");
                }else if(persona.getInfoV2() == null){
                    txtMostrarV1.setText(persona.getInfo());
                    txtMostrarV2.setText("No se ha vacunado");
                }else{
                    txtMostrarV1.setText(persona.getInfo());
                    txtMostrarV2.setText(persona.getInfoV2());
                }           
                
            }          
            
        }
        
        txtCUI.setText("");
        }
        
    }
    
    public static void imprimir() throws IOException{
        
    BufferedWriter writer = new BufferedWriter(new FileWriter("E:/Tareas Quinto Semestre/Programacion III/fichero.txt"));
    
    for (var entry : vacunados.entrySet()) {
        Personas persona = entry.getValue();
            
        writer.write(persona.getCui()+":"+persona.getInfo()+","+persona.getInfoV2()+"\n");
            
    }
    
    writer.close();
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCUI;
    private javax.swing.JLabel txtMostrar;
    private javax.swing.JLabel txtMostrarV1;
    private javax.swing.JLabel txtMostrarV2;
    // End of variables declaration//GEN-END:variables
}
